src/Entity/File.php
<?php

namespace App\Entity;

use App\Repository\FileRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=FileRepository::class)
 */
class File
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $location;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $filename;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="files")
     */
    private $user;

    /**
     * @ORM\ManyToOne(targetEntity=Article::class, inversedBy="files")
     */
    private $article;

    /**
     * @ORM\ManyToOne(targetEntity=Shop::class, inversedBy="files")
     */
    private $shop;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $mimeType;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $field;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLocation(): ?string
    {
        return $this->location;
    }

    public function setLocation(string $location): self
    {
        $this->location = $location;

        return $this;
    }

    public function getFilename(): ?string
    {
        return $this->filename;
    }

    public function setFilename(string $filename): self
    {
        $this->filename = $filename;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getArticle(): ?Article
    {
        return $this->article;
    }

    public function setArticle(?Article $article): self
    {
        $this->article = $article;

        return $this;
    }

    public function getShop(): ?Shop
    {
        return $this->shop;
    }

    public function setShop(?Shop $shop): self
    {
        $this->shop = $shop;

        return $this;
    }

    public function getMimeType(): ?string
    {
        return $this->mimeType;
    }

    public function setMimeType(string $mimeType): self
    {
        $this->mimeType = $mimeType;

        return $this;
    }

    public function getAbsolutePath(): ?string
    {
        return $this->location . DIRECTORY_SEPARATOR . $this->filename;
    }

    public function getRelativePath(): ?string
    {
        $relLoc = substr($this->location, strrpos($this->location, 'public/'));
        return str_replace('public', '', $relLoc) . DIRECTORY_SEPARATOR . $this->filename;
    }

    public function getField(): ?string
    {
        return $this->field;
    }

    public function setField(string $field): self
    {
        $this->field = $field;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $address;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $zipCode;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $phone;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isVerified = false;

    /**
     * @ORM\OneToOne(targetEntity=Shop::class, inversedBy="user", cascade={"persist", "remove"})
     */
    private $shop;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $firstname;

    /**
     * @ORM\OneToMany(targetEntity=File::class, mappedBy="user")
     */
    private $files;

    /**
     * @ORM\Column(type="boolean")
     */
    private $toDelete = false;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $verifToken;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $tokenValidity;

    public function __construct()
    {
        $this->files = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(?string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getZipCode(): ?string
    {
        return $this->zipCode;
    }

    public function setZipCode(?string $zipCode): self
    {
        $this->zipCode = $zipCode;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(?string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(?string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    public function getShop(): ?Shop
    {
        return $this->shop;
    }

    public function setShop(?Shop $shop): self
    {
        $this->shop = $shop;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(?string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(?string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getFullname(): ?string
    {
        return $this->firstname . ' ' . $this->name;
    }

    /**
     * @return Collection|File[]
     */
    public function getFiles(): Collection
    {
        return $this->files;
    }

    public function addFile(File $file): self
    {
        if (!$this->files->contains($file)) {
            $this->files[] = $file;
            $file->setUser($this);
        }

        return $this;
    }

    public function removeFile(File $file): self
    {
        if ($this->files->removeElement($file)) {
            // set the owning side to null (unless already changed)
            if ($file->getUser() === $this) {
                $file->setUser(null);
            }
        }

        return $this;
    }

    public function getToDelete(): ?bool
    {
        return $this->toDelete;
    }

    public function setToDelete(bool $toDelete): self
    {
        $this->toDelete = $toDelete;

        return $this;
    }

    public function getVerifToken(): ?string
    {
        return $this->verifToken;
    }

    public function setVerifToken(?string $verifToken): self
    {
        $this->verifToken = $verifToken;

        return $this;
    }

    public function getTokenValidity(): ?int
    {
        return $this->tokenValidity;
    }

    public function setTokenValidity(?int $tokenValidity): self
    {
        $this->tokenValidity = $tokenValidity;

        return $this;
    }
}

templates/partials/_article_card.html.twig
<div class="col-md-3 mb-3">
    <div class="card">
        <img class="card-img-top article-img" src="{{ article.mainImage.relativePath ?? '/assets/images/article-placeholder.png' }}" alt="Card image cap">
        <div class="card-body">
            <h5 class="card-title">{{ article.name }}</h5>
            <p class="card-text">{{ article.teaser|raw }}</p>
            <p class="card-text"><strong>{{ article.price }} €</strong> </p>
            <a href="{{ path('article_show', {shopSlug: shop.shopSlug, articleSlug: article.articleSlug}) }}" class="stretched-link"></a>
        </div>
    </div>
</div>

templates/partials/_footer.html.twig
<footer class="bg-light">
    <div class="container">
        <div class="row align-items-center justify-content-between py-3 text-center">
            <div class="col-md-2"><a href="{{ path('page', {type: 'cgu'}) }}">Conditions générales d'utilisation</a></div>
            <div class="col-md-2"><a href="#">Données personnelles</a></div>
            <div class="col-md-2"><a href="#">Cookies</a></div>
            <div class="col-md-2"><a href="mailto:admin@commerces-du-coin.fr">Contact</a></div>
            <div class="col-md-2"><a href="{{ path('page', {type: 'a-propos'}) }}">A propos</a></div>
        </div>
    </div>
</footer>

templates/partials/_navbar.html.twig
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">Mon shop local.fr</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/">Accueil</a>
      </li>
    </ul>
    <ul class="navbar-nav">
      {% if app.user %}
        {% if is_granted('ROLE_ADMIN') %}
          {% include "partials/_navbar_admin.html.twig" %}
        {% elseif is_granted('ROLE_MERCHANT') %}
          {% include "partials/_navbar_merchant.html.twig" %}
        {% else %}
          {% include "partials/_navbar_customer.html.twig" %}
        {% endif %}
      {% else %}
      <li class="nav-item">
        <a class="nav-link" href="{{ path('app_login') }}">Se connecter</a>
      </li>
      {% endif %}
    </ul>
    <div class="cartLine ml-lg-3 mt-2 mt-lg-0">
      <a href="{{ path('cart') }}">
        <svg width="1.5em" height="1.5em" viewBox="0 0 16 16" class="bi bi-bag" fill="currentColor"
          xmlns="http://www.w3.org/2000/svg">
          <path fill-rule="evenodd"
            d="M8 1a2.5 2.5 0 0 0-2.5 2.5V4h5v-.5A2.5 2.5 0 0 0 8 1zm3.5 3v-.5a3.5 3.5 0 1 0-7 0V4H1v10a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V4h-3.5zM2 5v9a1 1 0 0 0 1 1h10a1 1 0 0 0 1-1V5H2z" />
        </svg>
        <span class="articleCount">{{ cart_manager.getCartCount() }}</span>Article<span class="articlePlural">s</span>
      </a>
    </div>
  </div>
</nav>

templates/partials/_navbar_account.html.twig
<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
        aria-haspopup="true" aria-expanded="false">
        {{ app.user.fullname }}
    </a>
    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
        <a class="dropdown-item" href="{{ path('user_edit', {id: app.user.id}) }}">Mon compte</a>
        <div class="dropdown-divider"></div>
        <a class="dropdown-item" href="/logout">Se deconnecter</a>
    </div>
</li>

templates/partials/_navbar_admin.html.twig
{% include "partials/_navbar_account.html.twig" %}

templates/partials/_navbar_customer.html.twig
{% include "partials/_navbar_account.html.twig" %}

templates/partials/_navbar_merchant.html.twig
{% if app.user.shop is not empty %}
{% if not app.user.shop.isValid %}
<button type="button" class="btn btn-warning">Votre boutique est en cours d'activation</button>
{% endif %}
    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false">
            Ma boutique
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{{ path('order_index', {shopSlug: app.user.shop.shopSlug}) }}">Gérer les commandes</a>
            <a class="dropdown-item" href="{{ path('article_index', {shopSlug: app.user.shop.shopSlug}) }}">Gérer les articles</a>
            <a class="dropdown-item" href="{{ path('shop_edit', {shopSlug: app.user.shop.shopSlug}) }}">Modifier la boutique</a>
            <a class="dropdown-item" href="{{ path('shop_show', {shopSlug: app.user.shop.shopSlug}) }}">Voir la boutique</a>
        </div>
    </li>
{% else %}
    <li class="nav-item">
            <a class="nav-link" href="{{ path('shop_new') }}">Créer ma boutique</a>
    </li>
{% endif %}
{% include "partials/_navbar_account.html.twig" %}

templates/partials/_shop_card.html.twig
<div class="card mb-3">
    <img class="card-img-top home-img" src="{{ shop.mainImage.relativePath ?? '/assets/images/shop-placeholder.png' }}" alt="Card image cap">
    <div class="card-body">
        <h5 class="card-title">{{ shop.brand }}</h5>
        <p class="card-text">{{ shop.presentation|raw }}</p>
        <p class="card-text text-right"><small class="text-muted">{{ shop.city }} ({{ shop.zipCode }})</small></p>
        <a href="{{ path('shop_show', {shopSlug: shop.shopSlug}) }}" class="stretched-link"></a>
    </div>
</div>