src/Entity/Order.php
<?php

namespace App\Entity;

use App\Repository\OrderRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=OrderRepository::class)
 * @ORM\Table(name="`order`")
 */
class Order
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $total;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $customerName;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $customerFirstname;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $customerMail;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $customerPhone;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $CustomerAddress;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $customerZipCode;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $customerCity;

    /**
     * @ORM\Column(type="array", nullable=true)
     */
    private $content = [];

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $customerMessage;

    /**
     * @ORM\ManyToOne(targetEntity=Shop::class, inversedBy="orders")
     */
    private $shop;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $number;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getTotal(): ?float
    {
        return $this->total;
    }

    public function setTotal(?float $total): self
    {
        $this->total = $total;

        return $this;
    }

    public function getCustomerName(): ?string
    {
        return $this->customerName;
    }

    public function setCustomerName(string $customerName): self
    {
        $this->customerName = $customerName;

        return $this;
    }

    public function getCustomerFirstname(): ?string
    {
        return $this->customerFirstname;
    }

    public function setCustomerFirstname(?string $customerFirstname): self
    {
        $this->customerFirstname = $customerFirstname;

        return $this;
    }

    public function getCustomerMail(): ?string
    {
        return $this->customerMail;
    }

    public function setCustomerMail(string $customerMail): self
    {
        $this->customerMail = $customerMail;

        return $this;
    }

    public function getCustomerPhone(): ?string
    {
        return $this->customerPhone;
    }

    public function setCustomerPhone(?string $customerPhone): self
    {
        $this->customerPhone = $customerPhone;

        return $this;
    }

    public function getCustomerAddress(): ?string
    {
        return $this->CustomerAddress;
    }

    public function setCustomerAddress(?string $CustomerAddress): self
    {
        $this->CustomerAddress = $CustomerAddress;

        return $this;
    }

    public function getCustomerZipCode(): ?string
    {
        return $this->customerZipCode;
    }

    public function setCustomerZipCode(?string $customerZipCode): self
    {
        $this->customerZipCode = $customerZipCode;

        return $this;
    }

    public function getCustomerCity(): ?string
    {
        return $this->customerCity;
    }

    public function setCustomerCity(?string $customerCity): self
    {
        $this->customerCity = $customerCity;

        return $this;
    }

    public function getContent(): ?array
    {
        return $this->content;
    }

    public function setContent(?array $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getCustomerMessage(): ?string
    {
        return $this->customerMessage;
    }

    public function setCustomerMessage(?string $customerMessage): self
    {
        $this->customerMessage = $customerMessage;

        return $this;
    }

    public function getShop(): ?Shop
    {
        return $this->shop;
    }

    public function setShop(?Shop $shop): self
    {
        $this->shop = $shop;

        return $this;
    }

    public function getNumber(): ?string
    {
        return $this->number;
    }

    public function setNumber(string $number): self
    {
        $this->number = $number;

        return $this;
    }
}

src/Form/OrderType.php
<?php

namespace App\Form;

use App\Entity\Order;
use App\Form\AbstractForm;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;

class OrderType extends AbstractForm
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('customerFirstname', TextType::class, $this->setup('Prénom', false))
            ->add('customerName', TextType::class, $this->setup('Nom', false))
            ->add('customerMail', EmailType::class, $this->setup('Adresse e-mail', false))
            ->add('customerCity', TextType::class, $this->setup('Ville', false))
            ->add('customerZipCode', TextType::class, $this->setup('Code postal', false))
            ->add('CustomerAddress', TextType::class, $this->setup('Adresse', false))
            ->add('customerPhone', TextType::class, $this->setup('Numéro de téléphone', false))
            ->add('customerMessage', TextareaType::class, $this->setup('Message', false))
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Order::class,
        ]);
    }
}

src/Controller/OrderController.php
<?php

namespace App\Controller;

use App\Entity\Shop;
use App\Entity\Order;
use App\Form\OrderType;
use App\Service\Cart\CartManager;
use App\Repository\OrderRepository;
use App\Service\Utilities\Notifier;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

/**
 * @Route("/order")
 */
class OrderController extends AbstractController
{
    /**
     * @Route("/{shopSlug}/index", name="order_index", methods={"GET"})
     * @Security("is_granted('ROLE_ADMIN') or is_granted('ROLE_MERCHANT')")
     */
    public function index(Shop $shop, OrderRepository $orderRepository): Response
    {
        if ($this->getUser() !== $shop->getUser() && !$this->isGranted('ROLE_ADMIN')) {
            $this->addFlash('error', 'Action interdite');
        return $this->redirectToRoute('home', []);
        }

        return $this->render('order/index.html.twig', [
            'orders' => $orderRepository->findByShop($shop),
            'shop' => $shop,
        ]);
    }

    /**
     * @Route("/create/{shopSlug}", name="order_create", methods={"GET","POST"})
     */
    public function new(Shop $shop, Request $request, CartManager $cartManager, Notifier $notifier): Response
    {
        $cart = $cartManager->getFullCart();
        $sessionCart = $cartManager->getCart();
        $order = new Order();
        $form = $this->createForm(OrderType::class, $order);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $content = [];
            $content['shop'] = $shop->getAllInfos();
            foreach ($cart[$shop->getId()]['articles'] as $article) {
                $articleInfos = $article['article']->getAllInfos();
                $articleInfos['quantity'] = $article['quantity'];
                $content['articles'][] = $articleInfos;
                unset($sessionCart[$article['article']->getId()]);
            }

            $order
                ->setCreatedAt(new \DateTime())
                ->setNumber($shop->getId() . time())
                ->setTotal($cart[$shop->getId()]['totalPrice'])
                ->setShop($shop)
                ->setContent($content);


            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($order);
            $entityManager->flush();

            
            $notifier->notify('order_merchant', 'order_show', $order);
            $notifier->notify('order_customer', null, $order);

            $cartManager->setCart($sessionCart);

            return $this->redirectToRoute('shop_order_done', ['shopSlug' => $shop->getShopSlug()]);
        }

        return $this->render('order/new.html.twig', [
            'shopCart' => $cart[$shop->getId()],
            'order' => $order,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="order_show", methods={"GET"})
     * @Security("is_granted('ROLE_ADMIN') or is_granted('ROLE_MERCHANT')")
     */
    public function show(Order $order): Response
    {
        if ($this->getUser() !== $order->getShop()->getUser() && !$this->isGranted('ROLE_ADMIN')) {
            $this->addFlash('error', 'Action interdite');
        return $this->redirectToRoute('home', []);
        }

        return $this->render('order/show.html.twig', [
            'order' => $order,
        ]);
    }

    /**
     * @Route("/{id}", name="order_delete", methods={"DELETE"})
     * @Security("is_granted('ROLE_ADMIN') or is_granted('ROLE_MERCHANT')")
     */
    public function delete(Request $request, Order $order): Response
    {
        if ($this->getUser() !== $order->getShop()->getUser() && !$this->isGranted('ROLE_ADMIN')) {
            $this->addFlash('error', 'Action interdite');
        return $this->redirectToRoute('home', []);
        }

        if ($this->isCsrfTokenValid('delete'.$order->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($order);
            $entityManager->flush();
        }

        return $this->redirectToRoute('order_index');
    }
}

templates/order/_delete_form.html.twig
<form method="post" action="{{ path('order_delete', {'id': order.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ order.id) }}">
    <button class="btn">Delete</button>
</form>

templates/order/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-warning d-block w-50 mx-auto mb-3">{{ button_label|default('Commander !') }}</button>
{{ form_end(form) }}

templates/order/_order_table.html.twig
<table class="table table-striped table-responsive-md">
    <thead>
        <tr>
            <th scope="col">{% trans %}Article{% endtrans %}</th>
            <th scope="col">{% trans %}Prix{% endtrans %}</th>
            <th scope="col">{% trans %}Quantité{% endtrans %}</th>
            <th scope="col">{% trans %}Total{% endtrans %}</th>
        </tr>
    </thead>
    <tbody>
        {% for article in order.content.articles %}
        <tr>
            <td scope="row">{{ article.name }} {% if is_granted('ROLE_MERCHANT') %}(id : {{ article.id }}){% endif %}</td>
            <td class="ws-nowrap"><span class="cart-article-price">{{ article.price }}</span> €</td>
            <td class="cart-article-quantity">{{ article.quantity }}</td>
            <td class="ws-nowrap"><span class="cart-article-totalLine">{{ article.price * article.quantity }}</span> €</td>
        </tr>
        {% endfor %}
        <tr>
            <td scope="row" colspan="3" class="text-right ws-nowrap">{% trans %}Total :{% endtrans %}</td>
            <td class="ws-nowrap">{{ order.total }} €</td>
        </tr>
    </tbody>
</table>

templates/order/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Order{% endblock %}

{% block body %}
    <h1>Edit Order</h1>

    {{ include('order/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('order_index') }}">back to list</a>

    {{ include('order/_delete_form.html.twig') }}
{% endblock %}

templates/order/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Order index{% endblock %}

{% block body %}
<div class="container">
<h1 class="text-center my-4">{% trans %}Commandes reçues{% endtrans %}</h1>
    <table class="table table-striped table-responsive-md">
        <thead>
            <tr>
                <th>{% trans %}Numéro de commande{% endtrans %}</th>
                <th>{% trans %}Date{% endtrans %}</th>
                <th>{% trans %}Client{% endtrans %}</th>
                <th>{% trans %}Statut{% endtrans %}</th>
                <th>{% trans %}Montant{% endtrans %}</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for order in orders %}
            <tr>
                <td>{{ order.number }}</td>
                <td>{{ order.createdAt ? order.createdAt|date('Y-m-d H:i:s') : '' }}</td>
                <td><a href="mailto:{{ order.customerMail }}">{{ order.customerMail }}</a></td>
                <td  class="text-muted">A venir</td>
                <td class="ws-nowrap">{{ order.total }} €</td>
                <td>
                    <a href="{{ path('order_show', {'shopSlug': shop.shopSlug, 'id': order.id}) }}" class="btn btn-primary">Voir</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="15">{% trans %}Pas de commandes à afficher{% endtrans %}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    </div>
{% endblock %}

templates/order/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}{% trans %}Votre commande{% endtrans %}{% endblock %}
{% block stylesheets %}
<link rel="stylesheet" href="{{ asset('assets/css/cart.css') }}">
{% endblock %}
{% block body %}
<div class="container">
    <div class="jumbotron my-4">
        <h1>{{ shopCart.shop.brand }}</h1>
    </div>
    <h2 class="text-center my-4">{% trans %}Votre commande{% endtrans %}</h2>
        <div class="row">
            <div class="col-md-6">{{ include('cart/_cart_table.html.twig') }}</div>
            <div class="col-md-6">{{ include('order/_form.html.twig') }}</div>
        </div>
</div>

{% endblock %}

templates/order/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Commande{% endblock %}
{% block stylesheets %}<link rel="stylesheet" href="{{ asset('assets/css/order_show.css') }}">{% endblock %}
{% block body %}
<div class="container">
    <div class="jumbotron my-4">
        <h1>Commande du : {{ order.createdAt ? order.createdAt|date('d-m-Y \\à H:i') : '' }}</h1>
        <hr class="my-4">
        <p>Numéro de commande : {{ order.number }}</p>
    </div>
    <h2 class="text-center my-4">{% trans %}Détails de la commande{% endtrans %}</h1>
        <div class="row">
            <div class="col-md-6">{{ include('order/_order_table.html.twig') }}</div>
            <div class="col-md-6">
                <hr class="d-md-none">
                <p class="h3"><span class="h3 mr-2">{% include "icons/_black_person.html.twig" %}</span>{{ order.customerFirstname }} {{ order.customerName }}</p>
                <p class="h4"><span class="h3 mr-2">{% include "icons/_black_building.html.twig" %}</span>{{ order.customerAddress }}, {{ order.customerZipCode }} {{ order.customerCity }}</p>
                <p class="h4"><span class="h3 mr-2">{% include "icons/_black_envelope.html.twig" %}</span><a href="mailto:{{ order.customerMail }}">{{ order.customerMail }}</a></p>
                <p class="h4"><span class="h3 mr-2">{% include "icons/_black_telephone.html.twig" %}</span>{{ order.customerPhone }}</p>
                <p class="h4"><span class="h3 mr-2">{% include "icons/_black_chat_text.html.twig" %}</span>{{ order.customerMessage }}</p>
            </div>
        </div>
</div>
{% endblock %}